# Generated by Django 3.1.7 on 2021-03-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sku_name', models.CharField(max_length=30)),
                ('sku_category', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
